import { tinyassert } from "@hiogawa/utils";
import { describe, expect, it } from "vitest";
import { generateTypes } from "./generate-types";

describe("generateApi", () => {
  it("basic", async () => {
    const output = await generateTypes({
      skipNonTailwind: true,
    });
    const match = output.match(/type Theme_colors =(.*?);/ms);
    tinyassert(match);
    expect(match[0]).toMatchInlineSnapshot(`
      "type Theme_colors =
        | \`inherit\`
        | \`current\`
        | \`transparent\`
        | \`black\`
        | \`white\`
        | \`rose_1\`
        | \`rose_2\`
        | \`rose_3\`
        | \`rose_4\`
        | \`rose_5\`
        | \`rose_6\`
        | \`rose_7\`
        | \`rose_8\`
        | \`rose_9\`
        | \`rose_50\`
        | \`rose_100\`
        | \`rose_200\`
        | \`rose_300\`
        | \`rose_400\`
        | \`rose_500\`
        | \`rose_600\`
        | \`rose_700\`
        | \`rose_800\`
        | \`rose_900\`
        | \`rose_950\`
        | \`rose\`
        | \`pink_1\`
        | \`pink_2\`
        | \`pink_3\`
        | \`pink_4\`
        | \`pink_5\`
        | \`pink_6\`
        | \`pink_7\`
        | \`pink_8\`
        | \`pink_9\`
        | \`pink_50\`
        | \`pink_100\`
        | \`pink_200\`
        | \`pink_300\`
        | \`pink_400\`
        | \`pink_500\`
        | \`pink_600\`
        | \`pink_700\`
        | \`pink_800\`
        | \`pink_900\`
        | \`pink_950\`
        | \`pink\`
        | \`fuchsia_1\`
        | \`fuchsia_2\`
        | \`fuchsia_3\`
        | \`fuchsia_4\`
        | \`fuchsia_5\`
        | \`fuchsia_6\`
        | \`fuchsia_7\`
        | \`fuchsia_8\`
        | \`fuchsia_9\`
        | \`fuchsia_50\`
        | \`fuchsia_100\`
        | \`fuchsia_200\`
        | \`fuchsia_300\`
        | \`fuchsia_400\`
        | \`fuchsia_500\`
        | \`fuchsia_600\`
        | \`fuchsia_700\`
        | \`fuchsia_800\`
        | \`fuchsia_900\`
        | \`fuchsia_950\`
        | \`fuchsia\`
        | \`purple_1\`
        | \`purple_2\`
        | \`purple_3\`
        | \`purple_4\`
        | \`purple_5\`
        | \`purple_6\`
        | \`purple_7\`
        | \`purple_8\`
        | \`purple_9\`
        | \`purple_50\`
        | \`purple_100\`
        | \`purple_200\`
        | \`purple_300\`
        | \`purple_400\`
        | \`purple_500\`
        | \`purple_600\`
        | \`purple_700\`
        | \`purple_800\`
        | \`purple_900\`
        | \`purple_950\`
        | \`purple\`
        | \`violet_1\`
        | \`violet_2\`
        | \`violet_3\`
        | \`violet_4\`
        | \`violet_5\`
        | \`violet_6\`
        | \`violet_7\`
        | \`violet_8\`
        | \`violet_9\`
        | \`violet_50\`
        | \`violet_100\`
        | \`violet_200\`
        | \`violet_300\`
        | \`violet_400\`
        | \`violet_500\`
        | \`violet_600\`
        | \`violet_700\`
        | \`violet_800\`
        | \`violet_900\`
        | \`violet_950\`
        | \`violet\`
        | \`indigo_1\`
        | \`indigo_2\`
        | \`indigo_3\`
        | \`indigo_4\`
        | \`indigo_5\`
        | \`indigo_6\`
        | \`indigo_7\`
        | \`indigo_8\`
        | \`indigo_9\`
        | \`indigo_50\`
        | \`indigo_100\`
        | \`indigo_200\`
        | \`indigo_300\`
        | \`indigo_400\`
        | \`indigo_500\`
        | \`indigo_600\`
        | \`indigo_700\`
        | \`indigo_800\`
        | \`indigo_900\`
        | \`indigo_950\`
        | \`indigo\`
        | \`blue_1\`
        | \`blue_2\`
        | \`blue_3\`
        | \`blue_4\`
        | \`blue_5\`
        | \`blue_6\`
        | \`blue_7\`
        | \`blue_8\`
        | \`blue_9\`
        | \`blue_50\`
        | \`blue_100\`
        | \`blue_200\`
        | \`blue_300\`
        | \`blue_400\`
        | \`blue_500\`
        | \`blue_600\`
        | \`blue_700\`
        | \`blue_800\`
        | \`blue_900\`
        | \`blue_950\`
        | \`blue\`
        | \`sky_1\`
        | \`sky_2\`
        | \`sky_3\`
        | \`sky_4\`
        | \`sky_5\`
        | \`sky_6\`
        | \`sky_7\`
        | \`sky_8\`
        | \`sky_9\`
        | \`sky_50\`
        | \`sky_100\`
        | \`sky_200\`
        | \`sky_300\`
        | \`sky_400\`
        | \`sky_500\`
        | \`sky_600\`
        | \`sky_700\`
        | \`sky_800\`
        | \`sky_900\`
        | \`sky_950\`
        | \`sky\`
        | \`cyan_1\`
        | \`cyan_2\`
        | \`cyan_3\`
        | \`cyan_4\`
        | \`cyan_5\`
        | \`cyan_6\`
        | \`cyan_7\`
        | \`cyan_8\`
        | \`cyan_9\`
        | \`cyan_50\`
        | \`cyan_100\`
        | \`cyan_200\`
        | \`cyan_300\`
        | \`cyan_400\`
        | \`cyan_500\`
        | \`cyan_600\`
        | \`cyan_700\`
        | \`cyan_800\`
        | \`cyan_900\`
        | \`cyan_950\`
        | \`cyan\`
        | \`teal_1\`
        | \`teal_2\`
        | \`teal_3\`
        | \`teal_4\`
        | \`teal_5\`
        | \`teal_6\`
        | \`teal_7\`
        | \`teal_8\`
        | \`teal_9\`
        | \`teal_50\`
        | \`teal_100\`
        | \`teal_200\`
        | \`teal_300\`
        | \`teal_400\`
        | \`teal_500\`
        | \`teal_600\`
        | \`teal_700\`
        | \`teal_800\`
        | \`teal_900\`
        | \`teal_950\`
        | \`teal\`
        | \`emerald_1\`
        | \`emerald_2\`
        | \`emerald_3\`
        | \`emerald_4\`
        | \`emerald_5\`
        | \`emerald_6\`
        | \`emerald_7\`
        | \`emerald_8\`
        | \`emerald_9\`
        | \`emerald_50\`
        | \`emerald_100\`
        | \`emerald_200\`
        | \`emerald_300\`
        | \`emerald_400\`
        | \`emerald_500\`
        | \`emerald_600\`
        | \`emerald_700\`
        | \`emerald_800\`
        | \`emerald_900\`
        | \`emerald_950\`
        | \`emerald\`
        | \`green_1\`
        | \`green_2\`
        | \`green_3\`
        | \`green_4\`
        | \`green_5\`
        | \`green_6\`
        | \`green_7\`
        | \`green_8\`
        | \`green_9\`
        | \`green_50\`
        | \`green_100\`
        | \`green_200\`
        | \`green_300\`
        | \`green_400\`
        | \`green_500\`
        | \`green_600\`
        | \`green_700\`
        | \`green_800\`
        | \`green_900\`
        | \`green_950\`
        | \`green\`
        | \`lime_1\`
        | \`lime_2\`
        | \`lime_3\`
        | \`lime_4\`
        | \`lime_5\`
        | \`lime_6\`
        | \`lime_7\`
        | \`lime_8\`
        | \`lime_9\`
        | \`lime_50\`
        | \`lime_100\`
        | \`lime_200\`
        | \`lime_300\`
        | \`lime_400\`
        | \`lime_500\`
        | \`lime_600\`
        | \`lime_700\`
        | \`lime_800\`
        | \`lime_900\`
        | \`lime_950\`
        | \`lime\`
        | \`yellow_1\`
        | \`yellow_2\`
        | \`yellow_3\`
        | \`yellow_4\`
        | \`yellow_5\`
        | \`yellow_6\`
        | \`yellow_7\`
        | \`yellow_8\`
        | \`yellow_9\`
        | \`yellow_50\`
        | \`yellow_100\`
        | \`yellow_200\`
        | \`yellow_300\`
        | \`yellow_400\`
        | \`yellow_500\`
        | \`yellow_600\`
        | \`yellow_700\`
        | \`yellow_800\`
        | \`yellow_900\`
        | \`yellow_950\`
        | \`yellow\`
        | \`amber_1\`
        | \`amber_2\`
        | \`amber_3\`
        | \`amber_4\`
        | \`amber_5\`
        | \`amber_6\`
        | \`amber_7\`
        | \`amber_8\`
        | \`amber_9\`
        | \`amber_50\`
        | \`amber_100\`
        | \`amber_200\`
        | \`amber_300\`
        | \`amber_400\`
        | \`amber_500\`
        | \`amber_600\`
        | \`amber_700\`
        | \`amber_800\`
        | \`amber_900\`
        | \`amber_950\`
        | \`amber\`
        | \`orange_1\`
        | \`orange_2\`
        | \`orange_3\`
        | \`orange_4\`
        | \`orange_5\`
        | \`orange_6\`
        | \`orange_7\`
        | \`orange_8\`
        | \`orange_9\`
        | \`orange_50\`
        | \`orange_100\`
        | \`orange_200\`
        | \`orange_300\`
        | \`orange_400\`
        | \`orange_500\`
        | \`orange_600\`
        | \`orange_700\`
        | \`orange_800\`
        | \`orange_900\`
        | \`orange_950\`
        | \`orange\`
        | \`red_1\`
        | \`red_2\`
        | \`red_3\`
        | \`red_4\`
        | \`red_5\`
        | \`red_6\`
        | \`red_7\`
        | \`red_8\`
        | \`red_9\`
        | \`red_50\`
        | \`red_100\`
        | \`red_200\`
        | \`red_300\`
        | \`red_400\`
        | \`red_500\`
        | \`red_600\`
        | \`red_700\`
        | \`red_800\`
        | \`red_900\`
        | \`red_950\`
        | \`red\`
        | \`gray_1\`
        | \`gray_2\`
        | \`gray_3\`
        | \`gray_4\`
        | \`gray_5\`
        | \`gray_6\`
        | \`gray_7\`
        | \`gray_8\`
        | \`gray_9\`
        | \`gray_50\`
        | \`gray_100\`
        | \`gray_200\`
        | \`gray_300\`
        | \`gray_400\`
        | \`gray_500\`
        | \`gray_600\`
        | \`gray_700\`
        | \`gray_800\`
        | \`gray_900\`
        | \`gray_950\`
        | \`gray\`
        | \`slate_1\`
        | \`slate_2\`
        | \`slate_3\`
        | \`slate_4\`
        | \`slate_5\`
        | \`slate_6\`
        | \`slate_7\`
        | \`slate_8\`
        | \`slate_9\`
        | \`slate_50\`
        | \`slate_100\`
        | \`slate_200\`
        | \`slate_300\`
        | \`slate_400\`
        | \`slate_500\`
        | \`slate_600\`
        | \`slate_700\`
        | \`slate_800\`
        | \`slate_900\`
        | \`slate_950\`
        | \`slate\`
        | \`zinc_1\`
        | \`zinc_2\`
        | \`zinc_3\`
        | \`zinc_4\`
        | \`zinc_5\`
        | \`zinc_6\`
        | \`zinc_7\`
        | \`zinc_8\`
        | \`zinc_9\`
        | \`zinc_50\`
        | \`zinc_100\`
        | \`zinc_200\`
        | \`zinc_300\`
        | \`zinc_400\`
        | \`zinc_500\`
        | \`zinc_600\`
        | \`zinc_700\`
        | \`zinc_800\`
        | \`zinc_900\`
        | \`zinc_950\`
        | \`zinc\`
        | \`neutral_1\`
        | \`neutral_2\`
        | \`neutral_3\`
        | \`neutral_4\`
        | \`neutral_5\`
        | \`neutral_6\`
        | \`neutral_7\`
        | \`neutral_8\`
        | \`neutral_9\`
        | \`neutral_50\`
        | \`neutral_100\`
        | \`neutral_200\`
        | \`neutral_300\`
        | \`neutral_400\`
        | \`neutral_500\`
        | \`neutral_600\`
        | \`neutral_700\`
        | \`neutral_800\`
        | \`neutral_900\`
        | \`neutral_950\`
        | \`neutral\`
        | \`stone_1\`
        | \`stone_2\`
        | \`stone_3\`
        | \`stone_4\`
        | \`stone_5\`
        | \`stone_6\`
        | \`stone_7\`
        | \`stone_8\`
        | \`stone_9\`
        | \`stone_50\`
        | \`stone_100\`
        | \`stone_200\`
        | \`stone_300\`
        | \`stone_400\`
        | \`stone_500\`
        | \`stone_600\`
        | \`stone_700\`
        | \`stone_800\`
        | \`stone_900\`
        | \`stone_950\`
        | \`stone\`
        | \`light_1\`
        | \`light_2\`
        | \`light_3\`
        | \`light_4\`
        | \`light_5\`
        | \`light_6\`
        | \`light_7\`
        | \`light_8\`
        | \`light_9\`
        | \`light_50\`
        | \`light_100\`
        | \`light_200\`
        | \`light_300\`
        | \`light_400\`
        | \`light_500\`
        | \`light_600\`
        | \`light_700\`
        | \`light_800\`
        | \`light_900\`
        | \`light_950\`
        | \`light\`
        | \`dark_1\`
        | \`dark_2\`
        | \`dark_3\`
        | \`dark_4\`
        | \`dark_5\`
        | \`dark_6\`
        | \`dark_7\`
        | \`dark_8\`
        | \`dark_9\`
        | \`dark_50\`
        | \`dark_100\`
        | \`dark_200\`
        | \`dark_300\`
        | \`dark_400\`
        | \`dark_500\`
        | \`dark_600\`
        | \`dark_700\`
        | \`dark_800\`
        | \`dark_900\`
        | \`dark_950\`
        | \`dark\`
        | \`lightblue_1\`
        | \`lightblue_2\`
        | \`lightblue_3\`
        | \`lightblue_4\`
        | \`lightblue_5\`
        | \`lightblue_6\`
        | \`lightblue_7\`
        | \`lightblue_8\`
        | \`lightblue_9\`
        | \`lightblue_50\`
        | \`lightblue_100\`
        | \`lightblue_200\`
        | \`lightblue_300\`
        | \`lightblue_400\`
        | \`lightblue_500\`
        | \`lightblue_600\`
        | \`lightblue_700\`
        | \`lightblue_800\`
        | \`lightblue_900\`
        | \`lightblue_950\`
        | \`lightblue\`
        | \`lightBlue_1\`
        | \`lightBlue_2\`
        | \`lightBlue_3\`
        | \`lightBlue_4\`
        | \`lightBlue_5\`
        | \`lightBlue_6\`
        | \`lightBlue_7\`
        | \`lightBlue_8\`
        | \`lightBlue_9\`
        | \`lightBlue_50\`
        | \`lightBlue_100\`
        | \`lightBlue_200\`
        | \`lightBlue_300\`
        | \`lightBlue_400\`
        | \`lightBlue_500\`
        | \`lightBlue_600\`
        | \`lightBlue_700\`
        | \`lightBlue_800\`
        | \`lightBlue_900\`
        | \`lightBlue_950\`
        | \`lightBlue\`
        | \`warmgray_1\`
        | \`warmgray_2\`
        | \`warmgray_3\`
        | \`warmgray_4\`
        | \`warmgray_5\`
        | \`warmgray_6\`
        | \`warmgray_7\`
        | \`warmgray_8\`
        | \`warmgray_9\`
        | \`warmgray_50\`
        | \`warmgray_100\`
        | \`warmgray_200\`
        | \`warmgray_300\`
        | \`warmgray_400\`
        | \`warmgray_500\`
        | \`warmgray_600\`
        | \`warmgray_700\`
        | \`warmgray_800\`
        | \`warmgray_900\`
        | \`warmgray_950\`
        | \`warmgray\`
        | \`warmGray_1\`
        | \`warmGray_2\`
        | \`warmGray_3\`
        | \`warmGray_4\`
        | \`warmGray_5\`
        | \`warmGray_6\`
        | \`warmGray_7\`
        | \`warmGray_8\`
        | \`warmGray_9\`
        | \`warmGray_50\`
        | \`warmGray_100\`
        | \`warmGray_200\`
        | \`warmGray_300\`
        | \`warmGray_400\`
        | \`warmGray_500\`
        | \`warmGray_600\`
        | \`warmGray_700\`
        | \`warmGray_800\`
        | \`warmGray_900\`
        | \`warmGray_950\`
        | \`warmGray\`
        | \`truegray_1\`
        | \`truegray_2\`
        | \`truegray_3\`
        | \`truegray_4\`
        | \`truegray_5\`
        | \`truegray_6\`
        | \`truegray_7\`
        | \`truegray_8\`
        | \`truegray_9\`
        | \`truegray_50\`
        | \`truegray_100\`
        | \`truegray_200\`
        | \`truegray_300\`
        | \`truegray_400\`
        | \`truegray_500\`
        | \`truegray_600\`
        | \`truegray_700\`
        | \`truegray_800\`
        | \`truegray_900\`
        | \`truegray_950\`
        | \`truegray\`
        | \`trueGray_1\`
        | \`trueGray_2\`
        | \`trueGray_3\`
        | \`trueGray_4\`
        | \`trueGray_5\`
        | \`trueGray_6\`
        | \`trueGray_7\`
        | \`trueGray_8\`
        | \`trueGray_9\`
        | \`trueGray_50\`
        | \`trueGray_100\`
        | \`trueGray_200\`
        | \`trueGray_300\`
        | \`trueGray_400\`
        | \`trueGray_500\`
        | \`trueGray_600\`
        | \`trueGray_700\`
        | \`trueGray_800\`
        | \`trueGray_900\`
        | \`trueGray_950\`
        | \`trueGray\`
        | \`coolgray_1\`
        | \`coolgray_2\`
        | \`coolgray_3\`
        | \`coolgray_4\`
        | \`coolgray_5\`
        | \`coolgray_6\`
        | \`coolgray_7\`
        | \`coolgray_8\`
        | \`coolgray_9\`
        | \`coolgray_50\`
        | \`coolgray_100\`
        | \`coolgray_200\`
        | \`coolgray_300\`
        | \`coolgray_400\`
        | \`coolgray_500\`
        | \`coolgray_600\`
        | \`coolgray_700\`
        | \`coolgray_800\`
        | \`coolgray_900\`
        | \`coolgray_950\`
        | \`coolgray\`
        | \`coolGray_1\`
        | \`coolGray_2\`
        | \`coolGray_3\`
        | \`coolGray_4\`
        | \`coolGray_5\`
        | \`coolGray_6\`
        | \`coolGray_7\`
        | \`coolGray_8\`
        | \`coolGray_9\`
        | \`coolGray_50\`
        | \`coolGray_100\`
        | \`coolGray_200\`
        | \`coolGray_300\`
        | \`coolGray_400\`
        | \`coolGray_500\`
        | \`coolGray_600\`
        | \`coolGray_700\`
        | \`coolGray_800\`
        | \`coolGray_900\`
        | \`coolGray_950\`
        | \`coolGray\`
        | \`bluegray_1\`
        | \`bluegray_2\`
        | \`bluegray_3\`
        | \`bluegray_4\`
        | \`bluegray_5\`
        | \`bluegray_6\`
        | \`bluegray_7\`
        | \`bluegray_8\`
        | \`bluegray_9\`
        | \`bluegray_50\`
        | \`bluegray_100\`
        | \`bluegray_200\`
        | \`bluegray_300\`
        | \`bluegray_400\`
        | \`bluegray_500\`
        | \`bluegray_600\`
        | \`bluegray_700\`
        | \`bluegray_800\`
        | \`bluegray_900\`
        | \`bluegray_950\`
        | \`bluegray\`
        | \`blueGray_1\`
        | \`blueGray_2\`
        | \`blueGray_3\`
        | \`blueGray_4\`
        | \`blueGray_5\`
        | \`blueGray_6\`
        | \`blueGray_7\`
        | \`blueGray_8\`
        | \`blueGray_9\`
        | \`blueGray_50\`
        | \`blueGray_100\`
        | \`blueGray_200\`
        | \`blueGray_300\`
        | \`blueGray_400\`
        | \`blueGray_500\`
        | \`blueGray_600\`
        | \`blueGray_700\`
        | \`blueGray_800\`
        | \`blueGray_900\`
        | \`blueGray_950\`
        | \`blueGray\`
        | \`primary\`
      ;"
    `);
  });
});
