name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm -r build
      - run: pnpm -r test
      - run: pnpm -r generate-test
      - run: pnpm tsc
