name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint-check
      - run: pnpm build
      - run: pnpm test
      - run: pnpm tsc
      - run: pnpm example:generate-test
      - run: pnpm example:build
